#!/bin/bash
echo "🔐 GitHub Secrets Setup Helper"
echo "=============================="
echo ""
echo "📋 You need to add these 3 secrets to your GitHub repository:"
echo ""
echo "1. SERVER_IP = 3.84.224.16"
echo "2. SERVER_USER = ubuntu"
echo "3. SSH_PRIVATE_KEY = (see below)"
echo ""
echo "🚀 Steps to add secrets:"
echo "1. Go to: https://github.com/dcmcshan/MSAI/settings/secrets/actions"
echo "2. Click 'New repository secret' for each one"
echo "3. Copy the values below"
echo ""
echo "🔑 SSH_PRIVATE_KEY content:"
echo "=========================="
cat msai-production-key.pem
echo ""
echo "=========================="
echo ""
echo "✅ After adding all 3 secrets:"
echo "1. Go to Actions tab: https://github.com/dcmcshan/MSAI/actions"
echo "2. Click 'Run workflow' to trigger deployment"
echo "3. Watch the deployment progress"
echo ""
echo "🎯 Result: Application form will be live at http://msai.syzygyx.com/application"