version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.simple
    container_name: msai-web
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - DEBUG=False
      - ENVIRONMENT=production
    volumes:
      - ../app.py:/app/app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: msai-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.simple.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3